# Generated by Django 4.2.1 on 2023-05-13 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
