# Generated by Django 4.2.1 on 2023-05-18 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbapp', '0003_domain'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feature',
        ),
        migrations.AlterField(
            model_name='domain',
            name='d_desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
