# Generated by Django 4.2.1 on 2023-05-20 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbapp', '0006_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='e_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
    ]
