# Generated by Django 4.2.1 on 2023-05-23 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbapp', '0007_alter_events_e_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='email',
            field=models.EmailField(default=1, max_length=75),
            preserve_default=False,
        ),
    ]
