# Generated by Django 4.2.1 on 2023-05-23 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbapp', '0008_room_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='email',
        ),
    ]
